version: "3"
services:
  web:
    image: serversideup/php:8.4-cli
    ports:
      - "80:8080"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    command: php -S 0.0.0.0:8080 -t public
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nemon_db
      MYSQL_USER: nemon_user
      MYSQL_PASSWORD: nemon_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

